html pages created based on wireframes
INF7420/srinivasan-project pull request #8
Opened 2018-09-26 22:47 UTC by cd0868

2018-09-28 00:59 UTC, axamei requested changes

2018-09-28 00:59 UTC, axamei commented on about.html
> +<!--Begin Content-->
I recommend the use of `<main>` to distinguish the main portion of your page.

2018-09-28 00:59 UTC, axamei commented on about.html
> +<p>
If you do not intend to put text here, I would remove the paragraph element.

2018-09-28 00:59 UTC, axamei commented on index.html
> +      <h4>Freelance Web Developer</h4>
You should not skip heading levels. Some of your pages do not have an `<h3>` tag.

2018-09-28 00:59 UTC, axamei commented on about.html
> +    <nav><a href="index.html">Home</a> | <a href="portfolio.html">Portfolio</a> | <a href="ux.html">UX</a></nav>
The navigation menu should be an unordered list.

2018-10-10 20:57 UTC, cd0868 commented
I have made the required changes per your request.

2018-10-12 23:59 UTC, axamei approved these changes

2018-10-13 00:00 UTC, merged